# Generated by Django 3.2.3 on 2024-08-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_alter_cat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='cats/images/'),
        ),
    ]
